### ISSUE TITLE
removed documents doesn't propagated Meteor 1.8.1

### ISSUE THREAD

**Issue by DeanKamali** [robfallows/tunguska-reactive-aggregate#14]
Hey Rob, 

When I try and remove a document via meteor call / method, I'm seeing this exception on the server, also the document doesn't get removed on the frontend / "minimongo" . 

My meteor version is 1.8.1

Any ideas? 

```
W20190727-09:17:03.057(-4)? (STDERR) (node:49479) UnhandledPromiseRejectionWarning: Error: Removed nonexistent document 0
W20190727-09:17:03.057(-4)? (STDERR)     at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:202:17)
W20190727-09:17:03.057(-4)? (STDERR)     at Session.removed (packages/ddp-server/livedata_server.js:394:10)
W20190727-09:17:03.058(-4)? (STDERR)     at Subscription.removed (packages/ddp-server/livedata_server.js:1298:19)
W20190727-09:17:03.058(-4)? (STDERR)     at Subscription.subscriptionProto.(anonymous function) [as removed] (packages/montiapm:agent/lib/hijack/wrap_subscription.js:93:30)
W20190727-09:17:03.058(-4)? (STDERR)     at Object.keys.forEach.id (packages/tunguska:reactive-aggregate/aggregate.js:33:15)
W20190727-09:17:03.058(-4)? (STDERR)     at Array.forEach (<anonymous>)
W20190727-09:17:03.058(-4)? (STDERR)     at Promise.asyncApply (packages/tunguska:reactive-aggregate/aggregate.js:30:29)
W20190727-09:17:03.058(-4)? (STDERR)     at /Users/dean/.meteor/packages/promise/.0.11.2.1ixw4hn.8uhlk++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20190727-09:17:03.058(-4)? (STDERR) (node:49479) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
W20190727-09:17:03.059(-4)? (STDERR) (node:49479) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by robfallows** [comment]
@DeanKamali : I can't think of anything I've seen like this. Are you able to mock up a minimal reproduction, so I can investigate?

**Comment by robfallows** [comment]
Closing due to lack of feedback.
