### ISSUE TITLE
Exception in changedobserveChanges callback: Error: Cannot read property 'documents' of undefined

### ISSUE THREAD

**Issue by lc3t35** [robfallows/tunguska-reactive-aggregate#73]
Hi, I have this strange error (meteor 1.8, tunguska-reactive-aggregate 1.3.10)

```
2022-10-30 18:29:33+01:00 Exception in changedobserveChanges callback: Error: Cannot read property 'documents' of undefined
cr7ta
2022-10-30 18:29:33+01:00 at update (packages/tunguska:reactive-aggregate/aggregate.js:282:13)
cr7ta
2022-10-30 18:29:33+01:00 at debounce (packages/tunguska:reactive-aggregate/aggregate.js:301:7)
cr7ta
2022-10-30 18:29:33+01:00 at changed (packages/tunguska:reactive-aggregate/aggregate.js:323:9)
cr7ta
2022-10-30 18:29:33+01:00 at runWithEnvironment (packages/meteor.js:1347:24)
cr7ta
2022-10-30 18:29:33+01:00 at packages/meteor.js:1360:14
cr7ta
2022-10-30 18:29:33+01:00 at packages/mongo/observe_multiplex.js:178:30
cr7ta
2022-10-30 18:29:33+01:00 at Array.forEach (<anonymous>)
cr7ta
2022-10-30 18:29:33+01:00 at Function._.each._.forEach (packages/underscore.js:139:11)
cr7ta
2022-10-30 18:29:33+01:00 at Object.task (packages/mongo/observe_multiplex.js:172:9)
cr7ta
2022-10-30 18:29:33+01:00 at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:924:16)
cr7ta
2022-10-30 18:29:33+01:00 at packages/meteor.js:901:12
cr7ta
2022-10-30 18:29:34+01:00Exception in setTimeout callback: Error: Cannot read property 'documents' of undefined
cr7ta
2022-10-30 18:29:34+01:00 at update (packages/tunguska:reactive-aggregate/aggregate.js:282:13)
cr7ta
2022-10-30 18:29:34+01:00 at packages/tunguska:reactive-aggregate/aggregate.js:294:7
cr7ta
2022-10-30 18:29:34+01:00 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1259:12)
cr7ta
2022-10-30 18:29:34+01:00 at packages/meteor.js:557:25
cr7ta
2022-10-30 18:29:34+01:00 at runWithEnvironment (packages/meteor.js:1347:24)
```

**Comment by robfallows** [comment]
There's only one place in the code where that can appear:

https://github.com/robfallows/tunguska-reactive-aggregate/blob/65788b22bb71e122f2ebf44d216c453f4fbc950d/aggregate.js#L254

Is it possible there's no client collection defined?

**Comment by lc3t35** [comment]
FYI, I've updated existing meteor 2.2 to 2.8 and latest tunguska-reactive-aggregate 1.3.10 - you can edit the title of Readme still at 1.3.9)
clientCollection is optional ("defaults to the same name as the original collection"), so it is not defined in every aggregates in my code.
It should be by default : 
```
clientCollection: collection._name,
```

can we check if sub._session.collectionViews.get(localOptions.clientCollection) exist before getting .documents of it ? if not log : localOptions.clientCollection ?

**Comment by lc3t35** [comment]
here is the log : 

```
2022-11-02 10:17:18+01:00Settings updated for user : v...L
2022-11-02 14:55:35+01:00Settings updated for user : v...L
2022-11-02 16:10:57+01:00#73 localOptions.clientCollection : moments undefined
2022-11-02 16:10:57+01:00#73 localOptions.clientCollection : moments undefined
2022-11-02 16:10:57+01:00#73 localOptions.clientCollection : moments undefined
2022-11-02 16:10:57+01:00#73 localOptions.clientCollection : moments undefined
2022-11-02 16:10:57+01:00#73 localOptions.clientCollection : moments undefined
2022-11-02 16:10:57+01:00#73 localOptions.clientCollection : moments undefined
2022-11-02 16:10:57+01:00#73 localOptions.clientCollection : moments undefined
2022-11-02 16:10:57+01:00#73 localOptions.clientCollection : moments undefined
2022-11-02 16:10:57+01:00#73 localOptions.clientCollection : moments undefined
2022-11-02 16:10:57+01:00#73 localOptions.clientCollection : moments undefined
2022-11-02 16:10:57+01:00#73 localOptions.clientCollection : pensees undefined
2022-11-02 16:10:57+01:00#73 localOptions.clientCollection : pensees undefined
2022-11-02 16:10:57+01:00#73 localOptions.clientCollection : pensees undefined
2022-11-02 16:10:57+01:00#73 localOptions.clientCollection : pensees undefined
2022-11-02 16:10:57+01:00#73 localOptions.clientCollection : pensees undefined
2022-11-02 16:10:57+01:00#73 localOptions.clientCollection : pensees undefined
2022-11-02 16:10:57+01:00#73 localOptions.clientCollection : pensees undefined
2022-11-02 16:10:57+01:00#73 localOptions.clientCollection : pensees undefined
2022-11-02 16:10:57+01:00#73 localOptions.clientCollection : pensees undefined
2022-11-02 16:10:57+01:00#73 localOptions.clientCollection : pensees undefined
2022-11-02 16:10:58+01:00#73 localOptions.clientCollection : moments undefined
2022-11-02 16:10:58+01:00#73 localOptions.clientCollection : moments undefined
2022-11-02 16:10:58+01:00#73 localOptions.clientCollection : moments undefined
2022-11-02 16:10:58+01:00#73 localOptions.clientCollection : moments undefined
2022-11-02 16:10:58+01:00#73 localOptions.clientCollection : moments undefined
2022-11-02 16:10:58+01:00#73 localOptions.clientCollection : moments undefined
2022-11-02 16:10:58+01:00#73 localOptions.clientCollection : moments undefined
2022-11-02 16:10:58+01:00#73 localOptions.clientCollection : moments undefined
2022-11-02 16:10:58+01:00#73 localOptions.clientCollection : moments undefined
2022-11-02 16:10:58+01:00#73 localOptions.clientCollection : moments undefined
2022-11-02 16:12:21+01:00Settings updated for user : J...h
2022-11-02 16:17:49+01:00Settings updated for user : v...L
```
so we are losing sub._session.collectionViews ....

**Comment by robfallows** [comment]
Hmm. I've just checked the Meteor code - the use of `_` names on properties is always risky. However, it's still present.

What's your code for defining the publication?

**Comment by lc3t35** [comment]
the problem is not at `collection._name` (displayed in log as "moments", "pensees") but that `sub._session.collectionViews` is undefined

code : 
```
Meteor.publish(
  'moments.followedById',
  function (userId, limit = 5) {
    ....
    ReactiveAggregate(
      this,
      Moments,
      [ .... ],
      {
        noAutomaticObserver: true,
        debounceDelay: 100,
        observers: [
          Moments.find({}),
          Contacts.find({}),
          Contacts.find({
            $or: [
              { $where: 'this.followedBy.length >= 0' },
              { $where: 'this.following.length >= 0' },
              { $where: 'this.blocked.length >= 0' },
            ],
          }),
          Meteor.users.find({}),
        ],
      }
```

**Comment by robfallows** [comment]
Agreed, but there was a possibility that `this` was not valid (if you'd used `=>` instead of `function()`).

**Comment by lc3t35** [comment]
Thank you Rob for your time, if the user is disconnected for a few seconds, would this be the cause of the issue ?

**Comment by georgekovach** [comment]
Hello guys,

I've created a single-line [PR](https://github.com/robfallows/tunguska-reactive-aggregate/pull/78) which fixed this issue for me.
