### ISSUE TITLE
Still "Exception in changedobserveChanges callback: errorClass [Error]: Cannot read property 'documents' of undefined"

### ISSUE THREAD

**Issue by rambonette** [robfallows/tunguska-reactive-aggregate#76]
Hello @robfallows! Sorry to bother you, I'm having issues with the error reported in #73 even if I'm using `tunguska:reactive-aggregate@1.3.11` which should already be tackling this.

Error logs:
```
[my-server-ip]Exception in changedobserveChanges callback: errorClass [Error]: Cannot read property 'documents' of undefined
[my-server-ip]    at update (packages/tunguska:reactive-aggregate/aggregate.js:282:13)
[my-server-ip]    at debounce (packages/tunguska:reactive-aggregate/aggregate.js:301:7)
[my-server-ip]    at changed (packages/tunguska:reactive-aggregate/aggregate.js:323:9)
[my-server-ip]    at runWithEnvironment (packages/meteor.js:1486:24)
[my-server-ip]    at packages/meteor.js:1499:14
[my-server-ip]    at packages/mongo/observe_multiplex.js:178:30
[my-server-ip]    at Array.forEach (<anonymous>)
[my-server-ip]    at Function._.each._.forEach (packages/underscore.js:139:11)
[my-server-ip]    at Object.task (packages/mongo/observe_multiplex.js:172:9)
[my-server-ip]    at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:1026:16)
[my-server-ip]    at packages/meteor.js:1003:12 {
[my-server-ip]  path: '',
[my-server-ip]  sanitizedError: errorClass [Error]: tunguska:reactive-aggregate [Error]
[my-server-ip]      at errorClass.<anonymous> (packages/tunguska:reactive-aggregate/aggregate.js:11:27)
[my-server-ip]      at new errorClass (packages/meteor.js:718:17)
[my-server-ip]      at update (packages/tunguska:reactive-aggregate/aggregate.js:282:13)
[my-server-ip]      at debounce (packages/tunguska:reactive-aggregate/aggregate.js:301:7)
[my-server-ip]      at changed (packages/tunguska:reactive-aggregate/aggregate.js:323:9)
[my-server-ip]      at runWithEnvironment (packages/meteor.js:1486:24)
[my-server-ip]      at packages/meteor.js:1499:14
[my-server-ip]      at packages/mongo/observe_multiplex.js:178:30
[my-server-ip]      at Array.forEach (<anonymous>)
[my-server-ip]      at Function._.each._.forEach (packages/underscore.js:139:11)
[my-server-ip]      at Object.task (packages/mongo/observe_multiplex.js:172:9)
[my-server-ip]      at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:1026:16)
[my-server-ip]      at packages/meteor.js:1003:12 {
[my-server-ip]    isClientSafe: true,
[my-server-ip]    error: 'Error',
[my-server-ip]    reason: 'tunguska:reactive-aggregate',
[my-server-ip]    details: undefined,
[my-server-ip]    errorType: 'Meteor.Error'
[my-server-ip]  },
[my-server-ip]  errorType: 'tunguska:reactive-aggregate'
[my-server-ip]}
```

I'm currently publishing various `ReactiveAggregate()`s. To be honest, I only discovered this error by accident while casually checking the server logs. The system is in fact working correctly.

Could it be something related to the client's connection maybe?

Thanks

**Comment by robfallows** [comment]
Unfortunately, my day job is taking all my time at the moment. I'm happy to accept a PR 🙂

**Comment by JanMP** [comment]
What about Meteor 3.0? Is that taken care of?

**Comment by robfallows** [comment]
There is initial (untested) code in the `async-code` branch. Again, I've had no time to work on this.

**Comment by salmanhasni** [comment]
I had this similar issue, incase of you are using multiple `ReactiveAggregate` calls in single publish method that will cause the issue because the code track the subscription context against [aggregated method](https://github.com/robfallows/tunguska-reactive-aggregate/blob/master/aggregate.js#L265)  When oberver trys to remove the docs which doesn't exists. I assume its due to 1:1 map of `publish` context with `ReactiveAggregate`. Further if you are using multiple aggergation subscription and both have similar resultant id that will also cause the issue with initializing if the [doc](https://github.com/robfallows/tunguska-reactive-aggregate/blob/master/aggregate.js#L272C15-L272C22) with similar id is already called intialized.
to fix it my end, I have decoupled the multiple `ReactiveAggregate` in two different publish method 

**BEFORE**
```
Meteor.publish("new-pub, function() {
    ReactiveAggregate(this, collectionX, pipeline, {clientCollection: "A"})
    ReactiveAggregate(this, collectionX, pipeline, {clientCollection: "B"})
});
```

**AFTER**
```
Meteor.publish("new-pub1, function() {
    ReactiveAggregate(this, collectionX, pipeline, {clientCollection: "A"})
});
Meteor.publish("new-pub2, function() {
    ReactiveAggregate(this, collectionX, pipeline, {clientCollection: "B"})
});
```
