### ISSUE TITLE
Meteor 3 - TypeError: handle.stop is not a function

### ISSUE THREAD

**Issue by alisnic** [robfallows/tunguska-reactive-aggregate#89]
```
 at packages/tunguska:reactive-aggregate/aggregate.js:348:14
    at Array.forEach (<anonymous>)
    at Subscription.<anonymous> (packages/tunguska:reactive-aggregate/aggregate.js:347:13)
    at Subscription.<anonymous> (packages/meteor.js:1399:24)
    at packages/meteor.js:763:17
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.Meteor._runAsync (packages/meteor.js:760:14)
    at runWithEnvironment (packages/meteor.js:1392:21)
    at packages/meteor.js:1419:14
    at packages/ddp-server/livedata_server.js:1305:7
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:143:11)
    at Subscription._callStopCallbacks (packages/ddp-server/livedata_server.js:1304:7)
    at Subscription._deactivate (packages/ddp-server/livedata_server.js:1294:10)
    at Subscription.subscriptionProto._deactivate (packages/montiapm:agent/lib/hijack/wrap_subscription.js:95:24)
    at packages/ddp-server/livedata_server.js:1028:11
    at Map.forEach (<anonymous>)
    at Session._deactivateAllSubscriptions (packages/ddp-server/livedata_server.js:1027:21)
    at packages/ddp-server/livedata_server.js:542:12
    at EnvironmentVariableAsync.<anonymous> (packages/meteor.js:1292:16)
    at packages/meteor.js:763:17
    at AsyncLocalStorage.run (node:async_hooks:346:14)
```

I have package version 2.0.0 installed

**Comment by alisnic** [comment]
I think we should use `handles.push(await cursor.observeChangesAsync({` instead of `    `handles.push(cursor.observeChanges`, but I'm not sure.
